IF OBJECT_ID('SHOP', 'U') IS NOT NULL DROP TABLE SHOP;
IF OBJECT_ID('EMPLOYEE', 'U') IS NOT NULL DROP TABLE EMPLOYEE;
IF OBJECT_ID('REGULARCUSTOMER', 'U') IS NOT NULL DROP TABLE REGULARCUSTOMER;
IF OBJECT_ID('PRODUCT', 'U') IS NOT NULL DROP TABLE PRODUCT;
IF OBJECT_ID('TRANSACT', 'U') IS NOT NULL DROP TABLE TRANSACT;
IF OBJECT_ID('PRODUCTTRANSACT', 'U') IS NOT NULL DROP TABLE PRODUCTTRANSACT;

CREATE TABLE [dbo].[SHOP] (
    [Id]       INT          IDENTITY (1, 1) NOT NULL,
    [LOCATION] VARCHAR (30) NOT NULL,
    [Dbstate]  NUMERIC (1)  NOT NULL,
    CONSTRAINT [SHOP_PRIMARY_KEY] PRIMARY KEY CLUSTERED ([Id] ASC)
);





CREATE TABLE [dbo].[EMPLOYEE] (
    [Id]       INT           IDENTITY (1, 1) NOT NULL,
    [USERNAME] VARCHAR (10)  NOT NULL,
    [EMAIL]    VARCHAR (30)  NOT NULL,
    [ROLE]     NUMERIC (2)   NOT NULL,
    [PASSWORD] VARCHAR (MAX) NOT NULL,
    [Dbstate]  NUMERIC (1)   NOT NULL,
    CONSTRAINT [EMPLOYEE_PRIMARY_KEY] PRIMARY KEY CLUSTERED ([Id] ASC),
    UNIQUE NONCLUSTERED ([EMAIL] ASC),
    UNIQUE NONCLUSTERED ([USERNAME] ASC)
);







CREATE TABLE [dbo].[REGULARCUSTOMER] (
    [Id]           INT          IDENTITY (1, 1) NOT NULL,
    [EMAIL]        VARCHAR (30) NOT NULL,
    [CUSTOMERNAME] VARCHAR (30) NOT NULL,
    [Dbstate]      NUMERIC (1)  NOT NULL,
    CONSTRAINT [REGULARCUSTOMER_PRIMARY_KEY] PRIMARY KEY CLUSTERED ([Id] ASC),
    UNIQUE NONCLUSTERED ([EMAIL] ASC)
);





CREATE TABLE [dbo].[TRANSACT] (
    [Id]                INT         IDENTITY (1, 1) NOT NULL,
    [DATEOFTRANSACT]    DATE        NOT NULL,
    [ROLE]              NUMERIC (1) NOT NULL,
    [EMPID]             INT         NOT NULL,
    [REGULARCUSTOMERID] INT         NULL,
    [ORIGINSHOPID]      INT         NULL,
    [TARGETSHOPID]      INT         NULL,
    [Dbstate]           NUMERIC (1) NOT NULL,
    CONSTRAINT [TRANSACT_PRIMARY_KEY] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [TRANSACT_ORIGINSHOP_FOREIGN_KEY] FOREIGN KEY ([ORIGINSHOPID]) REFERENCES [dbo].[SHOP] ([Id]),
    CONSTRAINT [TRANSACT_TARGETSHOP_FOREIGN_KEY] FOREIGN KEY ([TARGETSHOPID]) REFERENCES [dbo].[SHOP] ([Id]),
    CONSTRAINT [TRANSACT_EMPID_FOREIGN_KEY] FOREIGN KEY ([EMPID]) REFERENCES [dbo].[EMPLOYEE] ([Id]),
    CONSTRAINT [TRANSACT_REGCUSTEMAIL_FOREIGN_KEY] FOREIGN KEY ([REGULARCUSTOMERID]) REFERENCES [dbo].[REGULARCUSTOMER] ([Id])
);





CREATE TABLE [dbo].[PRODUCT] (
    [Id]         INT          IDENTITY (1, 1) NOT NULL,
    [SHOPID]     INT          NOT NULL,
    [TRANSACTID] INT          NULL,
    [PRICE]      NUMERIC (8)  NOT NULL,
    [TYPE]       NUMERIC (2)  NOT NULL,
    [NAME]       VARCHAR (50) NOT NULL,
    [Dbstate]    NUMERIC (1)  NOT NULL,
    CONSTRAINT [PRODUCT_PRIMARY_KEY] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [PRODUCT_SHOP_FOREIGN_KEY] FOREIGN KEY ([SHOPID]) REFERENCES [dbo].[SHOP] ([Id]),
    CONSTRAINT [PRODUCT_TRANSACT_FOREIGN_KEY] FOREIGN KEY ([TRANSACTID]) REFERENCES [dbo].[TRANSACT] ([Id])
);



CREATE TABLE [dbo].[PRODUCTTRANSACT] (
    [PRODUCTID]  INT NOT NULL,
    [TRANSACTID] INT NOT NULL,
    CONSTRAINT [PRODUCTTRANSACT_PRODUCT_FOREIGN_KEY] FOREIGN KEY ([PRODUCTID]) REFERENCES [dbo].[PRODUCT] ([Id]),
    CONSTRAINT [PRODUCTTRANSACT_TRANSACT_FOREIGN_KEY] FOREIGN KEY ([TRANSACTID]) REFERENCES [dbo].[TRANSACT] ([Id])
);








INSERT INTO SHOP VALUES ('Budapest', 1);
INSERT INTO SHOP VALUES ('Debrecen', 1);
INSERT INTO SHOP VALUES ('Pécs', 1);
INSERT INTO SHOP VALUES ('Gyor', 1);
INSERT INTO SHOP VALUES ('Szolnok', 1);

INSERT INTO PRODUCT VALUES (1, NULL, 10000, 3, 'Fejhallgató', 1, NULL);
INSERT INTO PRODUCT VALUES (1, NULL, 15000, 1, '16 GB-os SD kártya', 1, NULL);
INSERT INTO PRODUCT VALUES (2, NULL, 230000, 2, 'Samsung Galaxy S3 Tab', 1, NULL);
INSERT INTO PRODUCT VALUES (2, NULL, 300000, 2, 'Fancy laptop', 1, NULL);
INSERT INTO PRODUCT VALUES (4, NULL, 100000, 5, 'Monitor', 1, NULL);