//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseOperations
{
    using System;
    using System.Collections.Generic;
    
    public partial class DISCOUNT
    {
        public int Id { get; set; }
        public string DISCOUNTDATA { get; set; }
        public System.DateTime DATE { get; set; }
        public int Dbstate { get; set; }
    }
}
