//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseOperations
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLOYEE()
        {
            this.TRANSACTs = new HashSet<TRANSACT>();
        }
    
        public int Id { get; set; }
        public string USERNAME { get; set; }
        public string EMAIL { get; set; }
        public int ROLE { get; set; }
        public string PASSWORD { get; set; }
        public int Dbstate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRANSACT> TRANSACTs { get; set; }

        public override string ToString()
        {
            return this.USERNAME;
        }
    }
}
