//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseOperations
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCT()
        {
            this.TRANSACTs = new HashSet<TRANSACT>();
        }
    
        public int Id { get; set; }
        public int SHOPID { get; set; }
        public Nullable<int> TRANSACTID { get; set; }
        public int PRICE { get; set; }
        public int TYPE { get; set; }
        public string NAME { get; set; }
        public int Dbstate { get; set; }
    
        public virtual SHOP SHOP { get; set; }
        public virtual TRANSACT TRANSACT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRANSACT> TRANSACTs { get; set; }

        //public override string ToString()
        //{
        //    return this.NAME + " " + this.PRICE;
        //}
    }
}
