//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseOperations
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSACT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TRANSACT()
        {
            this.PRODUCTs = new HashSet<PRODUCT>();
            this.PRODUCTs1 = new HashSet<PRODUCT>();
        }
    
        public int Id { get; set; }
        public System.DateTime DATEOFTRANSACT { get; set; }
        public int ROLE { get; set; }
        public int EMPID { get; set; }
        public Nullable<int> REGULARCUSTOMERID { get; set; }
        public Nullable<int> ORIGINSHOPID { get; set; }
        public Nullable<int> TARGETSHOPID { get; set; }
        public int Dbstate { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCT> PRODUCTs { get; set; }
        public virtual REGULARCUSTOMER REGULARCUSTOMER { get; set; }
        public virtual SHOP SHOP { get; set; }
        public virtual SHOP SHOP1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCT> PRODUCTs1 { get; set; }
    }
}
